version: '3.1'

services:
  teamcity:
    image: jetbrains/teamcity-server:2017.2.1
    volumes:
      - teamcity-server-datadir:/data/teamcity_server/datadir
      - teamcity-server-logs:/opt/teamcity/logs
    ports:
      - 8111:8111
    restart: unless-stopped
  teamcity-agent:
    image: aspnetcore/teamcity-agent-with-compose:2017.2.1
    build: ./agent
    environment:
      SERVER_URL: http://teamcity:8111
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  teamcity-server-datadir:
  teamcity-server-logs: